GIGACHAT_CREDENTIONALS="NTlkY2MyZmItM2Q4ZC00ZWMzLWE2NjAtNTI3MzZhOTk2ZjQzOjVhZGJiZDQxLTc0YjAtNDQxNi04YjAzLTUxZDVmYTY4NTkwNw"
source FLASK_APP='src/api'
source FLASK_ENV=development

flask run --host=0.0.0.0 --port=8080 --debug
